version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
      # postgres://db_ummf_user:n8VulyltfA0Ev2lkawD7AbLZYTVxWaCd@dpg-cp2dr8v79t8c73fs4ps0-a.oregon-postgres.render.com/db_ummf
      # postgresql://postgres:example@db:5432/postgres 
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server-container
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client-container